name: aplicativo_caa
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.11  # Dependência para usar SVGs

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/f7--chat-bubble-fill.svg  # Caminho do seu ícone SVG personalizado
